### PR TITLE
Add support for context option

### PR DESCRIPTION
**Pull request by nirmaoz**
Also refactor

### CODE REVIEW

**Comment by cortazar11** [comment]
Hi,

I am interested in your pull request. It seems the original don't have activity since long time.
So, I try to copy and paste your code straight away but no sure how to do it.
I follow these steps:
- Comment out the original plugin in the configuration (gatsby-config.js).
- Copy the utils.js file into my project and configure cloudinary with my details.
- Replace gatsby-node.js with your code.
- Re-install all the node modules.

It seems there is a first error in gatsby-node.js:
`
"gatsby-node.js" threw an error while running the sourceNodes lifecycle:
TypeError: Cannot read property 'api' of undefined

`
So, the nodes are no created.

**Comment by nirmaoz** [comment]
Thanks @cortazar11 I'll fix it soon

**Comment by nirmaoz** [comment]
@cortazar11 Fixed!
please remember to also copy package.json from this pr to the plugin folder

**Comment by cortazar11** [comment]
Hello,

Thank you for your code.
I check it. I clone your code and add up the libraries of Gatsby. So, the cloudinary nodes are created from scratch, without any other library.
The Graph IDE shows the cloudinary staff, but between the fields no any about the context. From the DEFAULT_KEYS of utils.js only shows resourceType and type.

As I am starting with Gatsby (and no too advanced in Development) I might be missing some steps:
- I need to require in some file of Gatsby (layout, pages) the sourceNodes exported in your gatsby-node.js file?
- I put in the configuration of "cloudinary" library the parameters context: true, but the result is the same. I need to put this option somewhere else?
- As Gatsby is client-side and the library "cloudinary" belongs to the Node.j SDK that is server-side, I need to organize the directories as a Full-Stack project? (Gatsby with their dependencies in a folder within a Node directory with their own dependencies)

**Comment by nirmaoz** [comment]
You need to add
context: true
to this source plugin options in gatsby-config.js

As for your other questions, gatsby builds your site on the server side (nodejs), and the result is client side code. You can read some of gatsby docs, or watch a youtube tutorial to understand more

**Comment by cortazar11** [comment]
Hi,

Yeap, I set a Gatsby project as usual and add a plugins directory.
In that directory I placed your code as a local plugin.
In gatsby-config.js I set a object with the resolve to the path where the local plugin is and set the options as in the original adding context: true.

Now, I can retrieve context => custom => caption with Graphql

Thank you for all

**Comment by nirmaoz** [comment]
great!

**Comment by Chuloo** [comment]
Thanks for the PR @nirmaoz amazing! 👍 👍

**Pull request merged**
